### ISSUE TITLE
Win64 link does not exists.

### ISSUE THREAD

**Issue by applibs** [angusfenying/memcached#1]
You have documented Win64 link to http://fenying.blog.163.com/
which does not exists anymore.
Can you update your documentation please?

**Comment by fenying** [comment]
Sorry about that. The 163.com has shutdown its blog service...

I'll post those old articles later on my new blog.

And here is a [memcached-win64 reference article ](http://www.cnblogs.com/greenlee/archive/2011/02/26/1965534.html), if you can't wait to see.
